version: '2'
services:
  web:
    build:
      context: ./
    image: eu.gcr.io/neso-io/sx-ember-wordpress
    environment:
      COURSES_API_URL: http://bifrost.local
    ports:
      - 4000:4000
  cache:
    image: jonbaldie/varnish:latest
    volumes:
      - ./varnish:/etc/varnish
    ports:
      - 8080:80

