apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: sx-ember-wordpress
spec:
 template:
   metadata:
     labels:
       name: sx-ember-wordpress
   spec:
     containers:
     - image: gcr.io/neso-io/sx-ember-wordpress:master
       name: sx-ember-wordpress
       env:
       - name: COURSES_API_URL
         valueFrom:
           configMapKeyRef:
             name: sx-ember-wordpress-config
             key: courses-api-url
       ports:
       - containerPort: 4000

