apiVersion: v1
kind: Service
metadata:
 name: sx-ember-wordpress
 labels:
   name: sx-ember-wordpress
   project-name: momentumhub

spec:
 ports:
   - port: 4000
     protocol: TCP
 selector:
   name: sx-ember-wordpress
 type: NodePort
