apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cache
  template:
    metadata:
      labels:
        name: cache
    spec:
      containers:
      - name: cache
        image: jonbaldie/varnish:latest
        volumeMounts:
        - name: template
          mountPath: /etc/varnish/default.vcl
          subPath: default.vcl
        - name: template
          mountPath: /etc/varnish/secret
          subPath: secret
      volumes:
      - name: template
        configMap:
          name: vcl-template
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vcl-template
data:
  secret: 2bc60cc9-1507-427b-a08a-164367e7f9b0
  default.vcl: |
    vcl 4.0;

    backend default {
        .host = "sx-ember-nginx";
        .port = "80";
    }

    sub vcl_recv {
        unset req.http.Cookie;
        if (req.method == "PRI") {
          /* We do not support SPDY or HTTP/2.0 */
          return (synth(405));
        }

        if (req.method != "GET" && req.method != "HEAD") {
            /* We only deal with GET and HEAD by default */
            return (pass);
        }

        if (req.http.Authorization || req.http.Cookie) {
            /* Not cacheable by default */
            return (pass);
        }
        set req.http.host = "www.systematix.co.uk";
        return (hash);
    }

    sub vcl_backend_fetch {
        return (fetch);
    }

    sub vcl_deliver {
        return (deliver);
    }


    sub vcl_backend_response {
        set beresp.ttl = 1w;
        set beresp.grace = 24h;
        if (beresp.ttl <= 0s ||
          beresp.http.Set-Cookie ||
          beresp.http.Surrogate-control ~ "no-store" ||
          (!beresp.http.Surrogate-Control &&
            beresp.http.Cache-Control ~ "no-cache|no-store|private") ||
          beresp.http.Vary == "*") {
            /*
            * Mark as "Hit-For-Pass" for the next 2 minutes
            */
            set beresp.ttl = 120s;
            set beresp.uncacheable = true;
        }
        return (deliver);
    }
---
apiVersion: v1
kind: Service
metadata:
 name: sx-cache
 labels:
   name: sx-cache
spec:
 ports:
   - port: 80
     protocol: TCP
 selector:
   name: cache
 type: NodePort
